# Generated by Django 4.2.25 on 2025-10-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='description',
        ),
        migrations.RemoveField(
            model_name='places',
            name='image',
        ),
        migrations.AddField(
            model_name='places',
            name='description_long',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='places',
            name='description_short',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='places',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=-1, max_digits=9),
        ),
        migrations.AddField(
            model_name='places',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=-1, max_digits=9),
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='map.places')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
